export const FAKE_COURSES = [
  {
    courseid: '1',
    category1: 'privacy',
    category2: 'ISO27001',
    skills: ['data', 'confidenitaly', 'PC-L1'],
    score_init: '1',
    score_complete: '10',
    score_pass: '30',
    duration: '300',
    url: 'https://aaaa',
    url_moile: 'https://aaaa',
    test_id: 'MC',
    test_url: 'https://aaaa',
    media: 'video',
    schedule_time: '2',
    schedule_day: '1',
    timestamp: '2021-10-26@14:09:25',
    mandatory: ['user'],
    cpd: ['cisa'],
    required_skills: [],
  },
  {
    courseid: '1',
    category1: 'privacy1',
    category2: 'ISO27001',
    skills: ['data', 'confidenitaly', 'PC-L1'],
    score_init: '1',
    score_complete: '10',
    score_pass: '30',
    duration: '300',
    url: 'https://aaaa',
    url_moile: 'https://aaaa',
    test_id: 'MC',
    test_url: 'https://aaaa',
    media: 'video',
    schedule_time: '2',
    schedule_day: '1',
    timestamp: '2021-10-26@14:09:25',
    mandatory: ['user'],
    cpd: ['cisa'],
    required_skills: [],
  },
  {
    courseid: '1',
    category1: 'privacy2',
    category2: 'ISO27001',
    skills: ['data', 'confidenitaly', 'PC-L1'],
    score_init: '1',
    score_complete: '10',
    score_pass: '30',
    duration: '300',
    url: 'https://aaaa',
    url_moile: 'https://aaaa',
    test_id: 'MC',
    test_url: 'https://aaaa',
    media: 'video',
    schedule_time: '2',
    schedule_day: '1',
    timestamp: '2021-10-26@14:09:25',
    mandatory: ['user'],
    cpd: ['cisa'],
    required_skills: [],
  },
  {
    courseid: '1',
    category1: 'privacy3',
    category2: 'ISO27001',
    skills: ['data', 'confidenitaly', 'PC-L1'],
    score_init: '1',
    score_complete: '10',
    score_pass: '30',
    duration: '300',
    url: 'https://aaaa',
    url_moile: 'https://aaaa',
    test_id: 'MC',
    test_url: 'https://aaaa',
    media: 'video',
    schedule_time: '2',
    schedule_day: '1',
    timestamp: '2021-10-26@14:09:25',
    mandatory: ['user'],
    cpd: ['cisa'],
    required_skills: [],
  },
  {
    courseid: '1',
    category1: 'privacy4',
    category2: 'ISO27001',
    skills: ['data', 'confidenitaly', 'PC-L1'],
    score_init: '1',
    score_complete: '10',
    score_pass: '30',
    duration: '300',
    url: 'https://aaaa',
    url_moile: 'https://aaaa',
    test_id: 'MC',
    test_url: 'https://aaaa',
    media: 'video',
    schedule_time: '2',
    schedule_day: '1',
    timestamp: '2021-10-26@14:09:25',
    mandatory: ['user'],
    cpd: ['cisa'],
    required_skills: [],
  },
]

export const FAKE_COURSE_HISTORY = [
  {
    courseid: '2',
    category1: 'integrity',
    category2: 'ISO',
    skills: ['data2', 'confidenitaly2', 'PC-L2'],
    score_init: '2',
    score_complete: '20',
    score_pass: '60',
    duration: '600',
    url: 'https://bbbb',
    url_moile: 'https://bbbb',
    test_id: 'MC2',
    test_url: 'https://bbbb',
    media: 'video2',
    schedule_time: '4',
    schedule_day: '2',
    timestamp: '2021-10-27@16:20:43',
    mandatory: ['user2'],
    cpd: ['cissp'],
    required_skills: [],
  },
]
