export const FAKE_COURSES = [
  {
    courseid: '1',
    category1: 'privacy',
    category2: 'ISO27001',
    skills: ['data', 'confidenitaly', 'PC-L1'],
    score_init: '1',
    score_complete: '10',
    score_pass: '30',
    duration: '300',
    url: 'https://aaaa',
    url_moile: 'https://aaaa',
    test_id: 'MC',
    test_url: 'https://aaaa',
    media: 'video',
    schedule_time: '2',
    schedule_day: '1',
    timestamp: '2021-11-04@14:55:35',
    mandatory: ['user'],
    cpd: ['cisa'],
    required_skills: [],
    thumbnail: 'https://api.hoplite.info/outlook_internal_staging_images/aho/courseid-1.png',
  },
  {
    courseid: '2',
    category1: 'integrity',
    category2: 'ISO',
    skills: ['data2', 'confidenitaly2', 'PC-L2'],
    score_init: '2',
    score_complete: '20',
    score_pass: '60',
    duration: '600',
    url: 'https://bbbb',
    url_moile: 'https://bbbb',
    test_id: 'MC2',
    test_url: 'https://bbbb',
    media: 'video2',
    schedule_time: '4',
    schedule_day: '2',
    timestamp: '2021-11-04@14:59:40',
    mandatory: ['user2'],
    cpd: ['cissp'],
    required_skills: [],
    thumbnail: 'https://api.hoplite.info/outlook_internal_staging_images/aho/courseid-2.png',
  },
  {
    courseid: '3',
    category1: 'integrity3',
    category2: 'ISO3',
    skills: ['data3', 'confidenitaly3', 'PC-L3'],
    score_init: '3',
    score_complete: '30',
    score_pass: '30',
    duration: '3600',
    url: 'https://cccc',
    url_moile: 'https://cccc',
    test_id: 'MC3',
    test_url: 'https://cccc',
    media: 'quiz3',
    schedule_time: '3',
    schedule_day: '3',
    thumbnail: null,
    timestamp: '2021-11-04@14:59:53',
    mandatory: ['user3'],
    cpd: ['cissp3'],
    required_skills: [],
  },
  {
    courseid: '4',
    category1: 'integrity4',
    category2: 'ISO4',
    skills: ['data4', 'confidenitaly4', 'PC-L4'],
    score_init: '4',
    score_complete: '40',
    score_pass: '40',
    duration: '4600',
    url: 'https://dddd',
    url_moile: 'https://dddd',
    test_id: 'MC4',
    test_url: 'https://dddd',
    media: 'quiz4',
    schedule_time: '4',
    schedule_day: '4',
    thumbnail: null,
    timestamp: '2021-11-04@15:00:04',
    mandatory: ['user4'],
    cpd: ['cissp4'],
    required_skills: [],
  },
  {
    courseid: '5',
    category1: 'integrity5',
    category2: 'ISO5',
    skills: ['data5', 'confidenitaly5', 'PC-L5'],
    score_init: '5',
    score_complete: '50',
    score_pass: '50',
    duration: '5600',
    url: 'https://eeee',
    url_moile: 'https://eeee',
    test_id: 'MC5',
    test_url: 'https://eeee',
    media: 'quiz5',
    schedule_time: '5',
    schedule_day: '5',
    thumbnail: null,
    timestamp: '2021-11-04@15:00:14',
    mandatory: ['user5'],
    cpd: ['cissp5'],
    required_skills: [],
  },
]

export const FAKE_COURSE_HISTORY = [
  {
    courseid: '2',
    category1: 'integrity',
    category2: 'ISO',
    skills: ['data2', 'confidenitaly2', 'PC-L2'],
    score_init: '2',
    score_complete: '20',
    score_pass: '60',
    duration: '600',
    url: 'https://bbbb',
    url_moile: 'https://bbbb',
    test_id: 'MC2',
    test_url: 'https://bbbb',
    media: 'video2',
    schedule_time: '4',
    schedule_day: '2',
    timestamp: '2021-10-27@16:20:43',
    mandatory: ['user2'],
    cpd: ['cissp'],
    required_skills: [],
  },
]
